#!/bin/bash
echo "Generating pages..."

cat > mkgallery.css << EOF
  .contents { 
    margin-right: 2em;
    margin-left: 2em;
    text-align: justify;
  }
  BODY {
    color: black;
    background: white;
  }
  DIV { margin-left: 0em; margin-right: 2em ; text-align: justify }
EOF

for file in index Download Examples Bugs TODO Thanks
do
if [ $file = "index" ]
  then
    title=""
    contents="<img src=\"images/MkGallery.jpg\" alt=\"\">"
  else
    title=" - "$file
    contents=$file
fi
  cat > "$file".html << EOF
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
  <title>MkGallery$title</title>
  <META HTTP-EQUIV="Content-Type" CONTENT="text/html; CHARSET=UTF-8">
  <link rel="stylesheet" href="mkgallery.css" type="text/css">
</head>
<body>
<br>
<table border=0  align="center" width=640 cellspacing="0" cellpadding="0">

<!-- borda superior -->
<tr>
  <td bgcolor="#A3BAFF"><img src="images/1.gif" alt="" width="20" height="20"></td>
  <td bgcolor="#A3BAFF" colspan="3"> &nbsp; </td>
  <td bgcolor="#A3BAFF"><img src="images/2.gif" alt="" width="20" height="20"></td>
</tr>

<!-- parte principal -->
<tr valign="top">
  <td bgcolor="#A3BAFF" width="16"> &nbsp; </td>
  
  <!-- Barra Esquerda -->
  <td bgcolor="#A3BAFF" width="128">
    <CENTER>
    <BR><b>MENU</b>
    <hr width=128 noshade>
    <BR>
    <b>
    <p><a href="index.html"><img src="images/Home.gif" border="0" alt=""></a><br><a href="index.html">Home</a></p>
    </b>
    <BR>
    <b>
    <p><a href="Download.html"><img src="images/Download.gif" border="0" alt=""></a><br><a href="Download.html">Download</a></p>
    </b>
    <BR>
    <b>
    <p><a href="Examples.html"><img src="images/Examples.gif" border="0" alt=""></a><br><a href="Examples.html">Examples</a></p>
    </b>
    <BR>
    <b>
    <p><a href="Bugs.html"><img src="images/Bugs.gif" border="0" alt=""></a><br><a href="Bugs.html">Bugs</a></p>
    </b>
    <BR>
    <b>
    <p><a href="TODO.html"><img src="images/TODO.gif" border="0" alt=""></a><br><a href="TODO.html">TODO</a></p>
    </b>
    <BR>
    <b>
    <p><a href="Thanks.html"><img src="images/Thanks.gif" border="0" alt=""></a><br><a href="Thanks.html">Thanks</a></p>
    </b>
    <BR>
    </CENTER>
  </td>
  <td bgcolor="#A3BAFF" width="16"> &nbsp; </td>
  
  <!-- Conteúdo -->
  <td bgcolor="#EEEEEE" width="464">
    <CENTER>
    <BR>
    <H3>$contents</H3>
    </CENTER>
EOF
if [ -r "$file"_html ]
  then 
  cat "$file"_html >> "$file".html
fi
  cat >> "$file".html << EOF
  </td>

  <td bgcolor="#A3BAFF" width="16"> &nbsp; </td>
</tr>

<!-- borda inferior -->
<tr>
  <td bgcolor="#A3BAFF"><img src="images/3.gif" alt="" width="20" height="20"></td>
  <td bgcolor="#A3BAFF" colspan="3"> &nbsp; </td>
  <td bgcolor="#A3BAFF"><img src="images/4.gif" alt="" width="20" height="20"></td>
</tr>
</table>

<br><br>

<table border=0  align="center" width=640 cellspacing="0" cellpadding="0">
<tr>
  <td align="left"><a href="https://github.com/jaafreitas">João Adriano Freitas</a></td>
  <td align="right"><A href="https://github.com/jaafreitas/mkgallery"><IMG src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png" width="31" height="31" border="0" alt="GitHub"></A></td>
</tr>
</table>

</body>
</html>
EOF
done
rm *~ >& /dev/null
