#!/bin/bash
# Adriano Freitas <afreitas@geocities.com>
# Version: 1.0pre1     http://www.geocities.com/jaafreitas/Linux/
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

total=`find *.jpg | grep -v "._" | wc -l | awk '{ printf $1 }'`
# find the amount of pictures in the current folder
pic_in_gallery=20	# how many picture per gallery?
gallery=1		# which gallery are we?
pic_number=1  # picture number
theme=gallery

do_maths()
{
if [ `echo $gallery*$pic_in_gallery|bc` -gt $total ]
  then
    untill=$total
  else
    untill=`echo $gallery*$pic_in_gallery|bc`
fi
echo -n "    <TD class=\"color2\" COLSPAN=\"7\">
      Showing `echo "($gallery-1)*$pic_in_gallery+1"|bc` - $untill of $total pictures" >> $theme$gallery".html"
previous=`expr $gallery - 1`
if [ $previous -gt 0 ]
  then
    if [ $previous -lt 10 ]
      then
        previous=0$previous
    fi
fi
next=`expr $gallery + 1`
if [ $gallery -le `expr $total / $pic_in_gallery` ]
  then
    if [ $next -lt 10 ]
      then
        next=0$next
    fi
  else
    next=0
fi
if [ $total -gt 20 ]
  then
    if [ $previous = 0 ]
      then
        echo -n " [ <FONT COLOR=\"gray\">&#171; Previous</FONT> | " >> $theme$gallery".html"
      else
        echo -n " [ <A HREF=\""$theme""$previous".html \">&#171; Previous</A> | " >> $theme$gallery".html"
    fi
    if [ $next = 0 ]
      then
        echo "<FONT COLOR=\"gray\">Next &#187;</FONT> ]" >> $theme$gallery".html"
      else
        echo "<A HREF=\""$theme""$next".html \">Next &#187;</A> ]" >> $theme$gallery".html"
    fi
fi
echo "    </TD>" >> $theme$gallery".html"
}

do_gallery_new_line()
{
cat >> $theme$gallery".html" << EOF
  </TR>
  <TR>
    <TD COLSPAN="7">
      &nbsp;
    </TD>
  </TR>
  <TR>
EOF
}

do_gallery_start()
{
echo $theme$gallery"..."
cat > $theme$gallery".html" << EOF
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
  <TITLE> $theme $gallery </TITLE>
  <META HTTP-EQUIV="Content-Type" CONTENT="text/html; CHARSET=iso-8859-1">
  <LINK REL="stylesheet" HREF="$theme.css" TYPE="text/css">
</HEAD>
<BODY>
<CENTER>
<TABLE WIDTH="90%" ALIGN="center">
  <TR>
    <TD class="color1" COLSPAN="7">
      <FONT class="color1"><B> $theme $gallery </B></FONT>
    </TD>
  </TR>
  <TR>
EOF
do_maths
do_gallery_new_line
}

do_gallery_end()
{
do_maths
cat >> $theme$gallery".html" << EOF
  </TR>
</TABLE>
</CENTER>
</BODY>
</HTML>
EOF
}

for pic in *.jpg
do
  if [ `expr $pic_number % $pic_in_gallery` = 1 ]
    then
      if [ $gallery -lt 10 ]
        then
	gallery=0$gallery
      fi
      do_gallery_start
      did_end=0;
  fi
  thumb="._"`echo $pic | sed 's/\.[^\.]*//'`.jpg
  echo -n "$pic "
  convert -quality 60 -depth 8 -density 72x72  -geometry 120x90 $pic $thumb 2>&1 > /dev/null
cat >> $theme$gallery".html" << EOF
    <TD WIDTH="22%" class="color2" ALIGN="center" VALIGN="baseline">
      <A HREF="$pic"><IMG SRC="$thumb" ALT="$pic" HSPACE="7" VSPACE="7"><BR>$pic</A>
    </TD>
EOF
  if [ `expr $pic_number % 4` = 0 ]
    then
      do_gallery_new_line
    else
      cat >> $theme$gallery".html" << EOF
    <TD WIDTH="4%">
      &nbsp;
    </TD>
EOF
  fi
  if [ `expr $pic_number % $pic_in_gallery` = 0 ]
    then
      do_gallery_end
      did_end=1
      gallery=`expr $gallery + 1`
      echo ""
  fi
  pic_number=`expr $pic_number + 1`
done
if [ $did_end = 0 ]
  then
    do_gallery_new_line
    do_gallery_end
fi
echo -e '\n'"CSS $theme..."
cat > $theme".css" << EOF
.color1 { color: white; background: #a3baff; }

.color2 { color: black; background: #eeeeee; }

B { text-transform: uppercase; }

TABLE { text-align: left; }

BODY 
{
  font-size: 12pt;
  font-family: Arial, Times, sans-serif;
  color: black;
  background: white;
}
EOF
